spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/telegram_bot
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

loader:
  daily-messages-path: data/daily-messages.json
  load-daily-messages: true

  sticker-sets-path: data/sticker_sets.txt
  load-stickers: true

  subreddits-path: data/subreddits.txt
  load-subreddits: true

  facts-path: data/facts.csv
  load-facts: true

bot:
  username: SheepLoverBot
  token: ${BOT_TOKEN}
  winner_name: pidor

  # daily schedule of winner
  schedule: 0 0 12 * * *
  # daily schedule of reset
  reset-schedule: 0 0 0 * * *

meme:
  api-url: https://meme-api.herokuapp.com/gimme
  download-path: temp/
  file-name: meme

  # hourly schedule of memes
  schedule: 0 0 * * * *
  # every minute schedule # commented
  #  schedule: 0 * * * * *

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
  jpa:
    show-sql: false
