spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/telegram_bot
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: update
      show-sql: true

loader:
  load-stickers: true
  load-daily-messages: true
  load-facts: true

bot:
  username: SheepLoverBot
  token: 6808027276:AAHear-Y_VmdZXnjOz10Gg0zWcs0YuBscv8
  winner_name: pidor

  # daily schedule of winner
  schedule: 0 0 12 * * *
  # daily schedule of reset
  reset-schedule: 0 0 0 * * *

  sticker_sets:
    - primates_uffchat
    - greatchurkobesfbi_by_fStikBot

meme:
  api-url: https://meme-api.herokuapp.com/gimme
  download-path: src/main/resources/temp/
  file-name: meme

  # hourly schedule of memes
  schedule: 0 0 * * * *
  # every minute schedule # commented
  #  schedule: 0 * * * * *
  # list of subredits to get memes from
  scheduled-subreddits:
    - wordington
    - wunkus
    - clamworks
