spring:
  datasource:
    url: jdbc:postgresql://localhost:6969/telegram_bot
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: update

loader:
  daily-messages-path: data/daily-messages.json
  load-daily-messages: true

  sticker-sets-path: data/sticker_sets.txt
  load-stickers: true

  subreddits-path: data/subreddits.txt
  load-subreddits: true

  facts-path: data/facts.csv
  load-facts: true

bot:
  # username: <<PROVIDE USING ENVIRONMENT VARIABLES>>
  # token: <<PROVIDE USING ENVIRONMENT VARIABLES>>
  # winner_name: <<PROVIDE USING ENVIRONMENT VARIABLES>>
  schedule: 0 0 12 * * *
  reset-schedule: 0 0 0 * * *

meme:
  api-url: https://meme-api.herokuapp.com/gimme
  download-path: /tmp/
  file-name: meme
  schedule: 0 0 * * * *
