spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/telegram_pibot
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: update
      show-sql: true

bot:
  username: SheepLoverBot
  token: 6808027276:AAHear-Y_VmdZXnjOz10Gg0zWcs0YuBscv8
  winner_name: pidor
  sticker_sets:
    - primates_uffchat
    - greatchurkobesfbi_by_fStikBot
meme:
  apiUrl: https://meme-api.herokuapp.com/gimme
  downloadPath: src/main/resources/temp
  fileName: meme.jpg
  # hourly schedule of memes
  schedule: 0 0 * * * *
