spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/telegram_pibot
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

bot:
  username: SheepLoverBot
  token: 6808027276:AAGWqNNwRoLJ3-NF6Mi0dbpJcrqOmqAGsHI
  sticker_sets:
    - primates_uffchat
    - greatchurkobesfbi_by_fStikBot
